channel_minimum_dbm: -80
channel_stat_num: 5
scan_stage_channel_time: 500
attack_stage_channel_time: 500
scan_round: 3

device: wlan0
drop_fcs: false

target_mac: "FF:FF:FF:FF:FF:FF"

channels: 
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 36
  - 40
  - 44
  - 48
  - 52
  - 56
  - 60
  - 64
  - 149
  - 153
  - 157
  - 161
  - 165 
